### ISSUE TITLE
Make the code public

### ISSUE THREAD

**Issue by Billy1900** [sferez/BybitMarketData#1]
hi, would you mind making your code public? I might could help some with the network issue you are currently facing.

**Comment by sferez** [comment]
Hi, [here](https://gist.github.com/sferez/acad718999ef26c74e2a496db758a37e) is the script. Really dummy code but it's working correctly

The network issue is just that I'm running the script locally and sometimes experience connection issues (not code-related)

I'm also late updating the data, I have a few months of data to upload here, so I need to find some time for that aha!

**Comment by Billy1900** [comment]
Thanks, I will take a look at that.
